import { Bellefair, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const bellefair = Bellefair({
  variable: "--font-bellefair",
  weight:['400'],
  subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  weight: ['400'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Frontend mentor | space tourism website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon/icon.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body
        className={`${bellefair.variable} ${barlowCondensed.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
